# Site settings
name: Mohammad Abdul Gafoor
title: Abdul Gafoor | The Developer
description: The OG developer building engaging digital experiences 
url: https://gafoor2005.github.io
baseurl: ''
email: gafoor@devloopers.me
cover: https://gafoor2005.github.io/img/og.png
logo: https://gafoor2005.github.io/img/emojis/technologist.png
resume: https://gafoor2005.github.io/resume.pdf
social:
  - title: email
    url: mailto:gafoor@devloopers.me
  - title: github
    url: https://github.com/gafoor2005
  - title: linkedin
    url: https://www.linkedin.com/in/Gafoor2005/
  - title: reddit
    url: https://www.reddit.com/u/Gafoor_/
  - title: twitter
    url: https://www.twitter.com/Gafoor__/
  - title: instagram
    url: https://www.instagram.com/developer.gg/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap

picture:
  source: img/
  output: resized_images/
  suppress_warnings: true